### ISSUE TITLE
有没浏览器插件形式的软件我们学校老师让交截图

### ISSUE THREAD

**Issue by luyaozhang00** [aqz236/hnzjdt#4]

**Comment by aqz236** [comment]
今晚更新版本  提交完后 生成截图文件

**Comment by aqz236** [comment]
js插件没写过，不过可以自己尝试实现，隔壁有js插件版本 不过一年没更新了，试试对接我这个题库

**Comment by TXaiCX** [comment]
需要题库吗我有，我不会往代码里填，跑完我才84分

**Comment by aqz236** [comment]
我们学校给的题库有的答案不一定对，这就很难受，你把你们题库也上传到github吧 我对比排查一下

**Comment by luyaozhang00** [comment]
[Uploading 宗教知识竞赛题283题.xlsx…]()

**Comment by luyaozhang00** [comment]
[Uploading 宗教知识竞赛题283题.xlsx…]()

**Comment by ctf513** [comment]
> 
可以发下题库吗

**Comment by aqz236** [comment]
> > 
> 
> 可以发下题库吗

https://github.com/aqz236/aqz236-hnzjtk

**Comment by TXaiCX** [comment]
发你邮箱吧，我小白不会上传

**Comment by ctf513** [comment]
> 发你邮箱吧，我小白不会上传

3225449809@qq.com  是学校给的题库嘛

**Comment by TXaiCX** [comment]
> [3225449809@qq.com](mailto:3225449809@qq.com)

算是吧，班长给的

**Comment by zykka** [comment]
大佬加油

**Comment by zykka** [comment]
大佬加油 我们学校也是让交截图

**Comment by aqz236** [comment]
家人们，新版本更新了  v1.6， 准确率稳定到了95% ，修复了匹配不到答案的bug，新增了截图生成工具。
